# Generated by Django 5.2.8 on 2025-11-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
