# Generated by Django 5.2.8 on 2025-11-21 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('categoria', models.CharField(choices=[('ELE', 'Eletrônicos'), ('ROU', 'Roupas'), ('LIV', 'Livros'), ('MOV', 'Móveis'), ('OUT', 'Outros')], default='OUT', help_text='Categoria do produto', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=16)),
                ('foto', models.ImageField(blank=True, help_text='Foto do produto', null=True, upload_to='fotos_produtos/')),
                ('descricao', models.TextField(help_text='Descrição do produto')),
                ('vendedor', models.ForeignKey(help_text='Vendedor do produto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
